// Auto-generated by F07
#ifndef MODEL_RESOLVER_H
#define MODEL_RESOLVER_H
#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"

inline void SetupModelResolver(tflite::MicroMutableOpResolver<50>& resolver) {
  resolver.AddCast();
  resolver.AddConv2D();
  resolver.AddDequantize();
  resolver.AddExpandDims();
  resolver.AddFullyConnected();
  resolver.AddGather();
  resolver.AddLogistic();
  resolver.AddQuantize();
  resolver.AddReduceMax();
  resolver.AddReshape();
}

#endif // MODEL_RESOLVER_H