// Auto-generated by F07
#ifndef MODEL_RESOLVER_H
#define MODEL_RESOLVER_H

#define MODEL_OPERATOR_COUNT 5

#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"

inline void SetupModelResolver(tflite::MicroMutableOpResolver<MODEL_OPERATOR_COUNT>& resolver) {
  resolver.AddDequantize();
  resolver.AddFullyConnected();
  resolver.AddLogistic();
  resolver.AddQuantize();
  resolver.AddReshape();
}

#endif