phase: f07_modval
variant: v701
platform: esp32
execution:
  project_dir: esp32_project
  runner_dir: null
time_scale_factor: 0.01
geometry:
  Tu_dataset: 10
  Tu_edge_ms: 100.0
  OW: 6
  LT: 1
  PW: 1
events:
  event_type_count: 221
drain:
  tu_ms: 100.0
  recommended_drain_seconds: 5.0
memory:
  arena_per_model: 20112
  arena_global: 24152
models:
- id: 0
  name: Battery_Active_Power_Set_Response_any-to-80_100-dense_bow-v501
  threshold: 0.3504415452480316
  itmax: 100
  mti_ms: 100
  arena_required: 20112
  model_size_bytes: 13408
  input_bytes: 91
  output_bytes: 1
prediction:
  name: Battery_Active_Power_Set_Response_any-to-80_100-dense_bow-v501
  threshold: 0.3504415452480316
operators:
- FULLY_CONNECTED
- LOGISTIC
- QUANTIZE
limits:
  MTI_MS: 100
  ITmax: 100
dataset:
  max_rows: null
