phase: f07_modval
variant: v701
parent: v601
parameters:
  parent_variant: v601
  time_scale_factor: 0.01
  Tu: 10
  OW: 6
  LT: 1
  PW: 1
  prediction_name: Battery_Active_Power_Set_Response_any-to-80_100
  decision_threshold: 0.590630054473877
  event_type_count: 221
  MTI_MS: 100
  platform: esp32
