phase: f07_modval
variant: v701
parent: v601
parameters:
  parent_variant: v601
  Tu: 10
  OW: 600
  LT: 100
  PW: 100
  prediction_name: Battery_Active_Power_any-to-80_100
  decision_threshold: 0.1768421083688736
  hardware_profile: esp32_default
