phase: f04_targets
variant: v402
parent: v301
parameters:
  parent_variant: v301
  Tu: 10
  OW: 600
  LT: 100
  PW: 100
  prediction_name: multi_event_target
  target_operator: OR
  target_event_types:
  - Battery_Active_Power_NaN_NaN
  - Battery_Active_Power_80_100-to-100_120
