phase: f04_targets
variant: v4_0080
parent: v3_0041
parameters:
  parent_variant: v3_0041
  Tu: 10
  OW: 90
  LT: 10
  PW: 10
  event_type_count: 30
  prediction_name: inlet_temperature_of_chilled_water_high_90_coarse_5
  target_operator: OR
  target_event_types:
  - Inlet_Temperature_of_Chilled_Water_0_10-to-90_100
  - Inlet_Temperature_of_Chilled_Water_10_25-to-90_100
  - Inlet_Temperature_of_Chilled_Water_25_50-to-90_100
  - Inlet_Temperature_of_Chilled_Water_50_75-to-90_100
  - Inlet_Temperature_of_Chilled_Water_75_90-to-90_100
parent_hashes:
  v3_0041: 0a104a14ac61cb080298f5956607241bd8aa9b5215cfaaac23023e9d91bf6bba
