phase: f04_targets
variant: v4_0042
parent: v3_0021
parameters:
  parent_variant: v3_0021
  Tu: 10
  OW: 50
  LT: 10
  PW: 10
  event_type_count: 20
  prediction_name: fc_active_power_low_20_fine_4
  target_operator: OR
  target_event_types:
  - FC_Active_Power_20_40-to-0_20
  - FC_Active_Power_40_60-to-0_20
  - FC_Active_Power_60_80-to-0_20
parent_hashes:
  v3_0021: 55d329d1b11214dd2f8f222437345363ed43c02d264b2659461c9e58d62b7d64
