phase: f07_modval
variant: v717
parent: v617
parameters:
  parent_variant: v617
  time_scale_factor: 0.01
  Tu: 10
  OW: 6
  LT: 1
  PW: 1
  prediction_name: FC_Active_Power_any-to-80_100
  decision_threshold: 0.3615439832210541
  event_type_count: 221
  MTI_MS: 100
  platform: esp32
