phase: f03_windows
variant: v3_0038
parent: v2_0011
parameters:
  parent_variant: v2_0011
  Tu: 10
  measure_name: MG-LV-MSB_AC_Voltage
  OW: 90
  LT: 10
  PW: 10
  window_strategy: synchro
  nan_mode: discard
parent_hashes:
  v2_0011: 897aa22fd6c2108f87cd52d33fab70d2b1a592284e4dd19c3c78f5dbbddd0e92
