phase: f04_targets
variant: v4_0055
parent: v3_0028
parameters:
  parent_variant: v3_0028
  Tu: 10
  OW: 90
  LT: 10
  PW: 10
  event_type_count: 90
  prediction_name: ge_active_power_high_90_coarse_10
  target_operator: OR
  target_event_types:
  - GE_Active_Power_0_10-to-90_100
  - GE_Active_Power_10_20-to-90_100
  - GE_Active_Power_20_30-to-90_100
  - GE_Active_Power_30_40-to-90_100
  - GE_Active_Power_40_50-to-90_100
  - GE_Active_Power_50_60-to-90_100
  - GE_Active_Power_60_70-to-90_100
  - GE_Active_Power_70_80-to-90_100
  - GE_Active_Power_80_90-to-90_100
parent_hashes:
  v3_0028: 51d7e1bda00bf8c6582e7b4a2ab1544afed212e27493557a49bee3e177b87b20
