phase: f05_modeling
variant: v501
artifacts:
  model:
    path: 05_modeling_model.h5
    sha256: ac06cc9dbeb3dae884a4e6b3c6da27fe2ea791c68efad14f147b4d8b6151c846
  labeled_dataset:
    path: 05_modeling_training_dataset.parquet
    sha256: 406a164dea2b1466dd8bc21b1ff26f00542634fd521b5c98f8c238517396d270
  history:
    path: 05_modeling_history.json
    sha256: c34397d51f4cf43f5fe2caf351dc78b1501a49257f141f58e511caf18acac8c0
  report:
    path: 05_modeling_report.html
    sha256: 56fb2a7e699540917d2d4c3eedb3565a02d94b21b3fcb955d2d3d71e1aa5bc20
exports:
  Tu: 10
  OW: 6
  LT: 1
  PW: 1
  prediction_name: Battery_Active_Power_Set_Response_any-to-80_100
  model_family: dense_bow
  decision_threshold: 0.631141722202301
  best_val_recall: 0.14285714285714285
  test_precision: 0.375
  test_recall: 0.21428571428571427
  test_f1: 0.2727272727272727
metrics:
  execution_time: 10.06427366702701
  n_train: 14066
  n_val: 3015
  n_test: 3015
  positive_ratio_train: 0.004834352338973411
  tp: 3
  tn: 2996
  fp: 5
  fn: 11
provenance:
  generated_at: '2026-03-18T10:43:58.586053+00:00'
  parent_phase: f04_targets
  parent_variant: v401
mlflow_registration:
  experiment_name: F05_Battery_Active_Power_Set_Response_any-to-80_100
  run_name: Battery_Active_Power_Set_Response_any-to-80_100__v501
  metrics:
    val_recall: 0.14285714285714285
    test_precision: 0.375
    test_recall: 0.21428571428571427
    test_f1: 0.2727272727272727
    test_tp: 3
    test_tn: 2996
    test_fp: 5
    test_fn: 11
  params:
    batch_size: 128
    learning_rate: 0.0005
    n_layers: 2
    units: 64
    dropout: 0.0
    model_family: dense_bow
  artifacts:
  - /Users/juancarlosduenaslopez/Documents/mlops/MLOps4OFP-FGCS/executions/f05_modeling/v501/05_modeling_model.h5
  - /Users/juancarlosduenaslopez/Documents/mlops/MLOps4OFP-FGCS/executions/f05_modeling/v501/05_modeling_history.json
  - /Users/juancarlosduenaslopez/Documents/mlops/MLOps4OFP-FGCS/executions/f05_modeling/v501/05_modeling_trials_summary.json
