phase: f07_modval
variant: v710
parent: v610
parameters:
  parent_variant: v610
  time_scale_factor: 0.01
  Tu: 10
  OW: 6
  LT: 1
  PW: 1
  prediction_name: Battery_Active_Power_any-to-80_100
  decision_threshold: 0.26571032404899597
  event_type_count: 221
  MTI_MS: 100
  platform: esp32
