phase: f04_targets
variant: v413
parent: v310
parameters:
  parent_variant: v310
  Tu: 10
  OW: 6
  LT: 1
  PW: 1
  event_type_count: 221
  prediction_name: GE_Active_Power_any-to-80_100
  target_operator: OR
  target_event_types:
  - GE_Active_Power_0_40-to-80_100
  - GE_Active_Power_40_60-to-80_100
  - GE_Active_Power_60_80-to-80_100
