phase: f07_modval
variant: v715
parent: v615
parameters:
  parent_variant: v615
  time_scale_factor: 0.01
  Tu: 10
  OW: 6
  LT: 1
  PW: 1
  prediction_name: GE_Body_Active_Power_Set_Response_any-to-80_100
  event_type_count: 221
  MTI_MS: 100
  platform: esp32
