phase: f08_sysval
variant: v803
platform: esp32
selection_mode: auto_ilp
execution:
  project_dir: esp32_project
  runner_dir: null
time_scale_factor: 0.01
geometry:
  Tu_dataset: 10
  Tu_edge_ms: 100.0
  OW: 6
  LT: 1
  PW: 1
events:
  event_type_count: 221
drain:
  tu_ms: 100.0
  recommended_drain_seconds: 5.0
memory:
  arena_per_model_max: 120840
  arena_global: 139990
  model_memory_payload_bytes: 252000
  model_memory_required_bytes: 284768
  memory_guard_bytes: 32768
  plate_available_heap_bytes: 316056
  fit_margin_bytes: 31288
  fits: true
models:
- id: 0
  name: Battery_Active_Power_any-to-80_100-cnn1d-v500
  threshold: 0.26571032404899597
  itmax: 34
  mti_ms: 100
  arena_required: 120840
  model_size_bytes: 80560
  input_bytes: 4
  output_bytes: 1
  model_id: Battery_Active_Power_any-to-80_100-cnn1d-v500__esp32
  parent_variant: v700
  prediction_name: Battery_Active_Power_any-to-80_100
  exec_time_ms: 34.0
- id: 1
  name: PVPCS_Active_Power_any-to-80_100-cnn1d-v502
  threshold: 0.36092594265937805
  itmax: 22
  mti_ms: 100
  arena_required: 75900
  model_size_bytes: 50600
  input_bytes: 5
  output_bytes: 1
  model_id: PVPCS_Active_Power_any-to-80_100-cnn1d-v502__esp32
  parent_variant: v702
  prediction_name: PVPCS_Active_Power_any-to-80_100
  exec_time_ms: 22.0
operators:
- CAST
- CONV_2D
- DEQUANTIZE
- EXPAND_DIMS
- FULLY_CONNECTED
- GATHER
- LOGISTIC
- REDUCE_MAX
- RESHAPE
limits:
  MTI_MS: 100
  ITmax: 34
dataset:
  source_unique_windows_csv: /Users/juancarlosduenaslopez/Documents/mlops/MLOps4OFP-FGCS/executions/f08_sysval/v803/08_unique_windows.csv
  max_rows: null
  unique_windows_count: 3275
