phase: f07_modval
variant: v716
parent: v616
parameters:
  parent_variant: v616
  time_scale_factor: 0.01
  Tu: 10
  OW: 6
  LT: 1
  PW: 1
  prediction_name: FC_Active_Power_FC_END_Set_any-to-80_100
  decision_threshold: 0.6166953444480896
  event_type_count: 221
  MTI_MS: 100
  platform: esp32
