phase: f04_targets
variant: v4_0019
parent: v3_0010
parameters:
  parent_variant: v3_0010
  Tu: 10
  OW: 50
  LT: 10
  PW: 10
  event_type_count: 90
  prediction_name: mg_lv_msb_ac_voltage_high_90_coarse_10
  target_operator: OR
  target_event_types:
  - MG-LV-MSB_AC_Voltage_0_10-to-90_100
  - MG-LV-MSB_AC_Voltage_10_20-to-90_100
  - MG-LV-MSB_AC_Voltage_20_30-to-90_100
  - MG-LV-MSB_AC_Voltage_30_40-to-90_100
  - MG-LV-MSB_AC_Voltage_40_50-to-90_100
  - MG-LV-MSB_AC_Voltage_50_60-to-90_100
  - MG-LV-MSB_AC_Voltage_60_70-to-90_100
  - MG-LV-MSB_AC_Voltage_70_80-to-90_100
  - MG-LV-MSB_AC_Voltage_80_90-to-90_100
parent_hashes:
  v3_0010: a1290fcd33ba92bc1fc52f852335eb579e59aef31f99b02001f2cb8b855fc0e3
