phase: f04_targets
variant: v4_0016
parent: v3_0008
parameters:
  parent_variant: v3_0008
  Tu: 10
  OW: 50
  LT: 10
  PW: 10
  event_type_count: 20
  prediction_name: mg_lv_msb_ac_voltage_low_20_fine_4
  target_operator: OR
  target_event_types:
  - MG-LV-MSB_AC_Voltage_20_40-to-0_20
  - MG-LV-MSB_AC_Voltage_40_60-to-0_20
  - MG-LV-MSB_AC_Voltage_60_80-to-0_20
parent_hashes:
  v3_0008: 0dd1ad72bab75f06d92b5969ad5bc2f05109fa21448e1101a031ca85d2077f43
