phase: f07_modval
variant: v712
platform: esp32
execution:
  project_dir: esp32_project
  runner_dir: null
time_scale_factor: 0.01
geometry:
  Tu_dataset: 10
  Tu_edge_ms: 100.0
  OW: 6
  LT: 1
  PW: 1
events:
  event_type_count: 221
drain:
  tu_ms: 100.0
  recommended_drain_seconds: 5.0
memory:
  arena_per_model: 75900
  arena_global: 88309
models:
- id: 0
  name: PVPCS_Active_Power_any-to-80_100-cnn1d-v512
  threshold: 0.36092594265937805
  itmax: 100
  mti_ms: 100
  arena_required: 75900
  model_size_bytes: 50600
  input_bytes: 5
  output_bytes: 1
prediction:
  name: PVPCS_Active_Power_any-to-80_100-cnn1d-v512
  threshold: 0.36092594265937805
operators:
- CAST
- CONV_2D
- DEQUANTIZE
- EXPAND_DIMS
- FULLY_CONNECTED
- GATHER
- LOGISTIC
- REDUCE_MAX
- RESHAPE
limits:
  MTI_MS: 100
  ITmax: 100
dataset:
  max_rows: null
